RININ363:warmup-exercise karthikey.dhandapani$ cat mysql.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
  namespace: mysql
spec:
  containers:
  - image: mysql/mysql-server
    name: mysql
    env:
    # Use secret in real usage
       - name: MYSQL_ROOT_PASSWORD
         value: password
    volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
   - name: mysql-persistent-storage
     hostPath:
       path: /data
       type: Directory 
